baseURL: "https://kantatamura.github.io/portfolio"
title: KantaTamura
paginate: 5
theme: PaperMod
canonifyurls: true

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true
#
#languages:
#  en:
#    languageName: "en"
#    weight: 1
#    profileMode:
#      enabled: true
#      title: Hello World
#      buttons:
#        - name: About
#          url: about
#        - name: Blog
#          url: posts
#        - name: Tags
#          url: tags
#    menu:
#      main:
#        - name: Archive
#          url: archives.md/
#          weight: 5
#        - name: Tags
#          url: tags
#          weight: 10
#        - name: Categories
#          url: categories
#          weight: 10
#        - name: Series
#          url: series
#          weight: 10
#        - name: NullLink
#          url: "#"
#        - name: NullLink2
#          url: "#"
#        - name: NullLink3
#          url: "#"

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "my portfolio"
  author: Me

  defaultTheme: dark
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  comments: false
  disableSpecial1stPost: false
  disableScrollToTop: false

  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"

  # profile-mode
  profileMode:
    enabled: true
    title: "Hello World"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/KantaTamura"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/KantaTamura/portfolio/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: archives
      name: archives
      url: archives
      weight: 10
    - identifier: series
      name: series
      url: series
      weight: 15
    - identifier: tags
      name: tags
      url: tags
      weight: 20
    - identifier: search
      name: search
      url: search
    - identifier: about
      name: about me
      url: about
      weight: 5
    - identifier: blog
      name: blog
      url: posts
      weight: 8


taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
